CREATE TABLE app_users (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE TABLE tasks (
 id BIGSERIAL PRIMARY KEY, title VARCHAR(150) NOT NULL, description VARCHAR(2000),
 status VARCHAR(20) NOT NULL DEFAULT 'TODO', priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
 due_date DATE, owner_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_tasks_owner_status ON tasks(owner_id,status);
